#!/bin/bash
#
# This is a script to run airflow webserver and scheduler at once.
#

DIR=${PWD}

if [ -z $APP_HOME ]; then
  if [ -f .env ]; then
    source .env
  else
    cd "$(dirname "${BASH_SOURCE[0]}" )"/../ > /dev/null 2>&1
  fi
fi

export TF_CPP_MIN_LOG_LEVEL=2

airflow scheduler -D
airflow webserver -D

echo "Waiting for Airflow webserver..."
while true; do
  _RUNNING=$(ps aux | grep airflow-webserver | grep ready | wc -l)
  if [ $_RUNNING -eq 0 ]; then
    sleep 1
  else
    echo "Airflow web server is ready"
    break;
  fi
done

cd ${DIR}
